name: Bug Issue
description: Informa un error en este modulo
title: "[BUG]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: tipo_error
    attributes:
      label: Tipo de error
      options:
        - label: Tecnico (Error HTTP explicito)
        - label: UX / Visual (Interfaz)
    validations:
      required: true

  - type: textarea
    id: descripcion
    attributes:
      label: Descripcion del problema
      placeholder: Reducción injusta de...
    validations:
      required: true

  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      placeholder: |
        1. Entrar a la pestaña de agentes y...
        2. Darle click a añadir agente cuando...
        3. Cerrar Sesión...
  
    validations:
      required: true

  - type: textarea
    id: esperado
    attributes:
      label: Comportamiento esperado
      placeholder: Deberia aparecer una venatana...
    validations:
      required: true

  - type: input
    id: entorno
    attributes:
      label: Dispositivo / Navegador / Entorno
      placeholder: Chrome en MacOS...
    validations:
      required: false

  - type: textarea
    id: evidencia
    attributes:
      label: Evidencia
    validations:
      required: false
