name: Task Issue
description: Tarea especifica derivada de una historia de usuario
title: "[TASK]: "
labels: ["task"]
body:
  - type: input
    id: user_story
    attributes:
      label: link/ID historia de usuario
    validations:
      required: false

  - type: textarea
    id: objetivo
    attributes:
      label: Objetivo
      placeholder: Crear el endpoint login...
    validations:
      required: true

  - type: textarea
    id: todo_list
    attributes:
      label: To-Do List
      placeholder: |
        1.
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: criterios_aceptacion
    attributes:
      label: Criterios de aceptacion
      placeholder: |
        1.
        2. 
        3.
  
    validations:
      required: true
