name: "User Story"
description: "Plantilla de usuario"
title: "[US]: "
labels: ["user-story"]
body:
  - type: textarea
    id: narrative
    attributes:
      label: "1. Descripción"
      placeholder: "Como [Rol], quiero [Acción], para [Beneficio]."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "2. Contexto o detalles adicionales"
      placeholder: "El emprendedor solo podrá... una vez..."
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: "3. Criterios de aceptación. "
      value: |
        - Dado que: 
        - Cuando: 
        - Entonces:
    validations:
      required: true